### ISSUE TITLE
syntax not being highlighted.

### ISSUE THREAD

**Issue by CaptainDaVinci** [jchouse/spacegray-atom-dark-syntax#10]
Syntax is not being highlighted as it used to, only plain text is obtained. 
atom version : 1.12.6

spacegray-atom-dark-syntax version : 1.3.1

UI : One Dark.

Initially, the syntax highlighting was working but after updating there seems to be an issue. I checked with other core syntax themes they all seem to be working.

**Comment by jchouse** [comment]
U need to upgrade atom version to 1.13.0, or downgrade package version to 1.2.0 apm install spacegray-atom-dark-syntax@1.2.0 http://flight-manual.atom.io/using-atom/sections/atom-packages/
