### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by JohanLeirnes** [jchouse/spacegray-atom-dark-syntax#11]
I get no syntax colors when using this.

Atom V.1.9.9

Theme V.1.3.1

**Comment by jchouse** [comment]
U need to upgrade Atom version to ^1.13.0, or downgrade package version to 1.2.0 apm install spacegray-atom-dark-syntax@1.2.0 http://flight-manual.atom.io/using-atom/sections/atom-packages/
