### ISSUE TITLE
Html syntax is just gray...

### ISSUE THREAD

**Issue by RoyalHunt** [jchouse/spacegray-atom-dark-syntax#6]
Hey there! After last update I get gray HTML syntax... It should to be like this? http://take.ms/ZJiki

http://take.ms/ed0E7

**Comment by jchouse** [comment]
U need to upgrade Atom version to ^1.13.0, or downgrade package version to 1.2.0 `apm install spacegray-atom-dark-syntax@1.2.0` http://flight-manual.atom.io/using-atom/sections/atom-packages/
