### ISSUE TITLE
All syntax is grey

### ISSUE THREAD

**Issue by zackjhuisman** [jchouse/spacegray-atom-dark-syntax#7]
All of my syntax is grey for html, sass, and css. this is one of my favorite syntax themes please fix soon thanks.

**Comment by jchouse** [comment]
U need to upgrade Atom version to 1.13.0, or downgrade package version to 1.2.0 `apm install spacegray-atom-dark-syntax@1.2.0` http://flight-manual.atom.io/using-atom/sections/atom-packages/
