### ISSUE TITLE
No colors displaying

### ISSUE THREAD

**Issue by claudioarchi** [jchouse/spacegray-atom-dark-syntax#8]
For a reason that I ignore the package, after the last update, does not display the txt in color all the code is in gey now.

Any idea?
<img width="948" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8075977/21917443/cd55d49a-d915-11e6-91ae-361746c86b2a.png">

**Comment by jchouse** [comment]
U need to upgrade atom version to 1.13.0, or downgrade package version to 1.2.0 `apm install spacegray-atom-dark-syntax@1.2.0` http://flight-manual.atom.io/using-atom/sections/atom-packages/
