### ISSUE TITLE
latest update causes problem with language-latex syntax highlighting

### ISSUE THREAD

**Issue by houghjosh** [jchouse/spacegray-atom-dark-syntax#9]
I'm not sure why this happened, but after updating to version 1.3.1, this theme no longer works in combination with `language-latex` syntax highlighting.

**Comment by jchouse** [comment]
U need to upgrade atom version to 1.13.0, or downgrade package version to 1.2.0 apm install spacegray-atom-dark-syntax@1.2.0 http://flight-manual.atom.io/using-atom/sections/atom-packages/
